version: "3"
services:
  webapi:
    image: idsrv4-webapi:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        env: ${DOCKER_ENV}
    container_name: minitis
    environment:
      # ASPNETCORE_ENVIRONMENT: Docker
      # ASPNETCORE_Kestrel__Certificates__Default__Password:
      # ASPNETCORE_Kestrel__Certificates__Default__Path: "/etc/docker/certs/docker.pfx"
    networks: 
      - default
    volumes:
      - ../idsrv4/webapi/Logs:/App_Data/Logs
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: idsrv4-redis
    volumes:
      - redis-data:/data
    ports:
       - ${REDIS_PORT}:6379
    expose: 
       - 6379
    command: ["redis-server", "--appendonly", "yes"]

networks:
  default:
    driver: bridge

volumes:
  redis-data: