---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-idsrv-pod
  labels:
    app: idsrv-demo
spec:
  containers:
    - name: kubernetes-idsrv-backend
      image: karatejb/idsrv4-backend
      ports:
        - containerPort: 5001
    # - name: kubernetes-idsrv-auth
    #   image: karatejb/idsrv4-auth
    #   ports:
    #     - containerPort: 6001
    # - name: kubernetes-idsrv-nginx
    #   image: karatejb/idsrv4-nginx
    #   ports:
    #     - containerPort: 5001
    #       name: auth
    #     - containerPort: 6001
    #       name: backend
