---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idsrv-demo-redis
    spec:
      hostname: idsrv-redis
      containers:
        - name: idsrv-redis
          image: redis:6.2
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      app: idsrv-demo-redis

---
apiVersion: v1
kind: Service
metadata:
  name: idsrv-redis
spec:
  selector:
    app: idsrv-demo-redis
  ports:
    - protocol: TCP
      port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idsrv-demo-openldap
    spec:
      containers:
        - name: idsrv-openldap
          image: osixia/openldap:stable
          ports:
            - containerPort: 389
  selector:
    matchLabels:
      app: idsrv-demo-openldap

---
apiVersion: v1
kind: Service
metadata:
  name: idsrv-openldap
spec:
  selector:
    app: idsrv-demo-openldap
  ports:
    - protocol: TCP
      port: 389

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: idsrv-demo-backend
    spec:
      containers:
        - name: idsrv-backend
          image: karatejb/idsrv4-backend
          ports:
            - containerPort: 5001
  selector:
    matchLabels:
      app: idsrv-demo-backend

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: idsrv-backend
# spec:
#   type: NodePort
#   selector:
#     app: idsrv-demo-backend
#   ports:
#     - protocol: TCP
#       port: 5001
#       targetPort: 5001
#       nodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-auth
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: idsrv-demo-auth
    spec:
      containers:
        - name: idsrv-auth
          image: karatejb/idsrv4-auth
          ports:
            - containerPort: 6001
  selector:
    matchLabels:
      app: idsrv-demo-auth
