---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idsrv-demo-redis
    spec:
      hostname: idsrv-redis
      containers:
        - name: idsrv-redis
          image: karatejbacr.azurecr.io/redis:6.2
          ports:
            - containerPort: 6379
      imagePullSecrets:
        - name: acrcred
  selector:
    matchLabels:
      app: idsrv-demo-redis

---
apiVersion: v1
kind: Service
metadata:
  name: idsrv-redis-service
spec:
  selector:
    app: idsrv-demo-redis
  ports:
    - protocol: TCP
      port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idsrv-demo-openldap
    spec:
      containers:
        - name: idsrv-openldap
          image: karatejbacr.azurecr.io/osixia/openldap:stable
          ports:
            - containerPort: 389
      imagePullSecrets:
        - name: acrcred
  selector:
    matchLabels:
      app: idsrv-demo-openldap

---
apiVersion: v1
kind: Service
metadata:
  name: idsrv-openldap-service
spec:
  selector:
    app: idsrv-demo-openldap
  ports:
    - protocol: TCP
      port: 389

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: idsrv-demo-backend
    spec:
      containers:
        - name: idsrv-backend
          image: karatejbacr.azurecr.io/idsrv4-backend
          ports:
            - containerPort: 5001
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Kubernetes"
          volumeMounts:
            - name: idsrv-backend-appsettings
              mountPath: /app
              readOnly: false
      imagePullSecrets:
        - name: acrcred
      volumes:
        - name: idsrv-backend-appsettings
          secret:
            secretName: secret-appsettings-backend
            defaultMode: 0755
  selector:
    matchLabels:
      app: idsrv-demo-backend

---
apiVersion: v1
kind: Service
metadata:
  name: idsrv-backend-service
spec:
  type: NodePort
  selector:
    app: idsrv-demo-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      # nodePort: 30501

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsrv-auth
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: idsrv-demo-auth
    spec:
      containers:
        - name: idsrv-auth
          image: karatejbacr.azurecr.io/idsrv4-auth
          ports:
            - containerPort: 6001
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Kubernetes"
          volumeMounts:
            - name: idsrv-auth-appsettings
              mountPath: /app
              readOnly: false
      imagePullSecrets:
        - name: acrcred
      volumes:
        - name: idsrv-auth-appsettings
          secret:
            secretName: secret-appsettings-auth
            defaultMode: 0755
  selector:
    matchLabels:
      app: idsrv-demo-auth

---
apiVersion: v1
kind: Service
metadata:
  name: idsrv-auth-service
spec:
  type: NodePort
  selector:
    app: idsrv-demo-auth
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
      # nodePort: 30601

# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: idsrv-ingress
#   labels:
#       name: idsrv-demo-ingress
# spec:
#   rules:
#     - host: jb.com
#       http:
#         paths:
#           - backend:
#               serviceName: idsrv-backend-service
#               servicePort: 5001 
#     - host: jb.com
#       http:
#         paths:
#           - backend:
#               serviceName: idsrv-auth-service
#               servicePort: 6001
