---
name: Publish Docker images
on:
  push:
      branches: 
        - master
        - dev
env:
  IMG_AUTH: is-auth
  IMG_BACKEND: is-backend
  IMG_NGINX: is-nginx
  IMG_TAG_DEFAULT: latest
jobs:
  push_images_to_dockerhub:
    name: Push images to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push auth
        id: build_publish_auth
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/auth.dockerfile
          push: true
          tags: registry.xaas.ar/${{ env.IMG_AUTH }}:${{ env.IMG_TAG_DEFAULT }}
      # - name: Image digest
      #   run: echo ${{ steps.build_publish_auth.outputs.digest }}
      - name: Build and push backend
        id: build_publish_backend
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/backend.dockerfile
          push: true
          tags: registry.xaas.ar/${{ env.IMG_BACKEND }}:${{ env.IMG_TAG_DEFAULT }}
      - name: Build and push nginx
        id: build_publish_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/nginx.dockerfile
          push: true
          tags: registry.xaas.ar/${{ env.IMG_NGINX }}:${{ env.IMG_TAG_DEFAULT }}
