---
name: Publish Docker images
on:
  push:
      branches: [ master, k8s-support ]
jobs:
  push_images_to_dockerhub:
    name: Push images to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push auth
        id: build_publish_auth
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/auth.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/idsrv4-auth:latest
      # - name: Image digest
      #   run: echo ${{ steps.build_publish_auth.outputs.digest }}
      - name: Build and push backend
        id: build_publish_backend
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/backend.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/idsrv4-backend:latest
      - name: Build and push nginx
        id: build_publish_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/nginx.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/idsrv4-nginx:latest
  push_images_to_acr:
    name: Push images to ACR
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push auth
        id: build_publish_auth
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/auth.dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/idsrv4-auth:latest
      - name: Build and push backend
        id: build_publish_backend
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/backend.dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/idsrv4-backend:latest
      - name: Build and push nginx
        id: build_publish_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/nginx.dockerfile
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/idsrv4-nginx:latest
      - name: Pull and push openldap
        id: publish_openldap
        run: |
          docker pull osixia/openldap:stable
          docker tag osixia/openldap:stable ${{ secrets.ACR_REGISTRY }}/openldap:stable
          docker push ${{ secrets.ACR_REGISTRY}}/openldap:stable
