---
name: Publish Docker images
on:
  push:
      branches: [ master, k8s-support ]
jobs:
  push_auth_to_repository:
    name: Push Auth image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push auth
        id: build_publish_auth
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/auth.dockerfile
          push: true
          tags: karatejb/idsrv4-auth:latest
      - name: Image digest
        run: echo ${{ steps.build_publish_auth.outputs.digest }}
      - name: Build and push backend
        id: build_publish_backend
        uses: docker/build-push-action@v2
        with:
          # context: .
          file: ./docker/backend.dockerfile
          push: true
          tags: karatejb/idsrv4-backend:latest
      - name: Image digest
        run: echo ${{ steps.build_publish_backend.outputs.digest }}
      - name: Build and push nginx
        id: build_publish_nginx
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/nginx.dockerfile
          push: true
          tags: karatejb/idsrv4-nginx:latest
      - name: Image digest
        run: echo ${{ steps.build_publish_nginx.outputs.digest }}
